// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class ICU4XMeasureUnit implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  ICU4XMeasureUnit._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_ICU4XMeasureUnit_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_ICU4XMeasureUnit_destroy_mv1));

  /// Parse a [ICU4XMeasureUnit] from a string.
  ///
  /// Throws [DataError] on failure.
  static ICU4XMeasureUnit deserialize(String s) {
    final temp = _FinalizedArena();
    final result = _icu4x_ICU4XMeasureUnit_deserialize_mv1(s._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return ICU4XMeasureUnit._fromFfi(result.union.ok, []);
  }

}

@_DiplomatFfiUse('icu4x_ICU4XMeasureUnit_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_ICU4XMeasureUnit_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_ICU4XMeasureUnit_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_ICU4XMeasureUnit_deserialize_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(_SliceUtf8)>(isLeaf: true, symbol: 'icu4x_ICU4XMeasureUnit_deserialize_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_ICU4XMeasureUnit_deserialize_mv1(_SliceUtf8 s);

// dart format on
