// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class ICU4XUnitsConverterFactory implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  ICU4XUnitsConverterFactory._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_ICU4XUnitsConverterFactory_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_ICU4XUnitsConverterFactory_destroy_mv1));

  /// Create a new [ICU4XUnitsConverterFactory] with compiled data.
  ///
  /// See the [Rust documentation for `new`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.new) for more information.
  factory ICU4XUnitsConverterFactory() {
    final result = _icu4x_ICU4XUnitsConverterFactory_create_mv1();
    return ICU4XUnitsConverterFactory._fromFfi(result, []);
  }

  /// Create a new [ICU4XUnitsConverterFactory] with a data provider.
  ///
  /// See the [Rust documentation for `try_new_with_buffer_provider`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.try_new_with_buffer_provider) for more information.
  ///
  /// Throws [DataError] on failure.
  factory ICU4XUnitsConverterFactory.withProvider(DataProvider provider) {
    final result = _icu4x_ICU4XUnitsConverterFactory_create_with_provider_mv1(provider._ffi);
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return ICU4XUnitsConverterFactory._fromFfi(result.union.ok, []);
  }

  /// Create a new [ICU4XUnitsConverter] for the given input and output units.
  ICU4XUnitsConverter? converter(ICU4XMeasureUnit inputUnit, ICU4XMeasureUnit outputUnit) {
    final result = _icu4x_ICU4XUnitsConverterFactory_converter_mv1(_ffi, inputUnit._ffi, outputUnit._ffi);
    return result.address == 0 ? null : ICU4XUnitsConverter._fromFfi(result, []);
  }

}

@_DiplomatFfiUse('icu4x_ICU4XUnitsConverterFactory_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_ICU4XUnitsConverterFactory_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_ICU4XUnitsConverterFactory_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_ICU4XUnitsConverterFactory_create_mv1')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function()>(isLeaf: true, symbol: 'icu4x_ICU4XUnitsConverterFactory_create_mv1')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _icu4x_ICU4XUnitsConverterFactory_create_mv1();

@_DiplomatFfiUse('icu4x_ICU4XUnitsConverterFactory_create_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_ICU4XUnitsConverterFactory_create_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_ICU4XUnitsConverterFactory_create_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider);

@_DiplomatFfiUse('icu4x_ICU4XUnitsConverterFactory_converter_mv1')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_ICU4XUnitsConverterFactory_converter_mv1')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _icu4x_ICU4XUnitsConverterFactory_converter_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> inputUnit, ffi.Pointer<ffi.Opaque> outputUnit);

// dart format on
