// generated by diplomat-tool
import { DataError } from "./DataError.mjs"
import { DataProvider } from "./DataProvider.mjs"
import { ICU4XMeasureUnit } from "./ICU4XMeasureUnit.mjs"
import { ICU4XUnitsConverter } from "./ICU4XUnitsConverter.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const ICU4XUnitsConverterFactory_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.icu4x_ICU4XUnitsConverterFactory_destroy_mv1(ptr);
});

export class ICU4XUnitsConverterFactory {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("ICU4XUnitsConverterFactory is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            ICU4XUnitsConverterFactory_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Create a new {@link ICU4XUnitsConverterFactory} with compiled data.
     *
     * See the [Rust documentation for `new`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.new) for more information.
     */
    #defaultConstructor() {

        const result = wasm.icu4x_ICU4XUnitsConverterFactory_create_mv1();

        try {
            return new ICU4XUnitsConverterFactory(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Create a new {@link ICU4XUnitsConverterFactory} with a data provider.
     *
     * See the [Rust documentation for `try_new_with_buffer_provider`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.try_new_with_buffer_provider) for more information.
     */
    static createWithProvider(provider) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_ICU4XUnitsConverterFactory_create_with_provider_mv1(diplomatReceive.buffer, provider.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DataError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('DataError.' + cause.value, { cause });
            }
            return new ICU4XUnitsConverterFactory(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Create a new {@link ICU4XUnitsConverter} for the given input and output units.
     */
    converter(inputUnit, outputUnit) {

        const result = wasm.icu4x_ICU4XUnitsConverterFactory_converter_mv1(this.ffiValue, inputUnit.ffiValue, outputUnit.ffiValue);

        try {
            return result === 0 ? null : new ICU4XUnitsConverter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Create a new {@link ICU4XUnitsConverterFactory} with compiled data.
     *
     * See the [Rust documentation for `new`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.new) for more information.
     */
    constructor() {
        if (arguments[0] === diplomatRuntime.exposeConstructor) {
            return this.#internalConstructor(...Array.prototype.slice.call(arguments, 1));
        } else if (arguments[0] === diplomatRuntime.internalConstructor) {
            return this.#internalConstructor(...arguments);
        } else {
            return this.#defaultConstructor(...arguments);
        }
    }
}