// generated by diplomat-tool
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { ICU4XMeasureUnit } from "./ICU4XMeasureUnit"
import type { ICU4XUnitsConverter } from "./ICU4XUnitsConverter"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ICU4XUnitsConverterFactory {
    /** @internal */
    get ffiValue(): pointer;


    /**
     * Create a new {@link ICU4XUnitsConverterFactory} with a data provider.
     *
     * See the [Rust documentation for `try_new_with_buffer_provider`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.try_new_with_buffer_provider) for more information.
     */
    static createWithProvider(provider: DataProvider): ICU4XUnitsConverterFactory;

    /**
     * Create a new {@link ICU4XUnitsConverter} for the given input and output units.
     */
    converter(inputUnit: ICU4XMeasureUnit, outputUnit: ICU4XMeasureUnit): ICU4XUnitsConverter | null;

    /**
     * Create a new {@link ICU4XUnitsConverterFactory} with compiled data.
     *
     * See the [Rust documentation for `new`](https://docs.rs/icu/2.2.0/icu/units/converter_factory/struct.ConverterFactory.html#method.new) for more information.
     */
    constructor();
}