// generated by diplomat-tool
import type { DataError } from "./DataError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ICU4XMeasureUnit {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Parse a {@link ICU4XMeasureUnit} from a string.
     */
    static deserialize(s: string): ICU4XMeasureUnit;
}